FROM centos:8

RUN dnf clean all

# Base dnf configuration.
RUN echo 'http_caching=none' >> /etc/yum.conf && \
    echo 'assumeyes=1' >> /etc/yum.conf && \
    sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf && \
    dnf install -y dnf-plugins-core
RUN dnf config-manager --set-enabled powertools
RUN curl -o centreon-release.rpm "http://yum-1.centreon.com/standard/21.10/el8/stable/noarch/RPMS/centreon-release-21.10-1.el8.noarch.rpm"
RUN dnf install --nogpgcheck centreon-release.rpm
RUN dnf config-manager --set-enabled 'centreon-testing*'
RUN dnf clean all && dnf install -y cmake \
    gcc \
    gcc-c++ \
    gettext \
    git \
    MariaDB-devel \
    gnutls-devel \
    libgcrypt-devel \
    libssh2-devel \
    lua-devel \
    make \
    maven \
    perl-ExtUtils-Embed.noarch \
    libssh2-devel \
    python3-pip \
    perl-Thread-Queue \
    redhat-lsb \
    rpm-build \
    rrdtool-devel \
    yum-utils \
    MariaDB-shared \
    perl \
    rpm-build
RUN dnf update libarchive

RUN pip3 install conan --prefix=/usr --upgrade
RUN rm -rf ~/.conan/profiles/default
RUN echo -e '\
[requires]\n\
gtest/cci.20210126\n\
asio/1.18.1\n\
fmt/7.1.3\n\
spdlog/1.8.5\n\
nlohmann_json/3.9.1\n\
openssl/1.1.1l\n\
grpc/1.37.0\n\
mariadb-connector-c/3.1.12\n\
zlib/1.2.11\n\
[generators]\n\
cmake_paths\n\
cmake_find_package\n\
' > conanfile.txt
RUN conan install . -s compiler.libcxx=libstdc++11 --build='*'
    
WORKDIR /src